import os
import subprocess
import sys
import threading

# Folder where Buddy saves what he learns
SKILLS_DIR = "learned_skills"
os.makedirs(SKILLS_DIR, exist_ok=True)

class SkillManager:
    def __init__(self):
        pass

    def learn_new_skill(self, task_name, python_code):
        """
        Takes raw Python code generated by Llama 3, saves it as a reusable script.
        """
        # 1. Clean filename
        filename = "".join([c for c in task_name if c.isalnum() or c=='_']).lower() + ".py"
        filepath = os.path.join(SKILLS_DIR, filename)

        # 2. Save the code
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(python_code)
        
        return filepath

    def execute_skill(self, task_name):
        """
        Runs a script Buddy learned previously.
        """
        filename = "".join([c for c in task_name if c.isalnum() or c=='_']).lower() + ".py"
        filepath = os.path.join(SKILLS_DIR, filename)

        if not os.path.exists(filepath):
            return f"I haven't learned how to {task_name} yet."

        try:
            # Run the script in a subprocess so it doesn't crash the main Avatar
            result = subprocess.check_output([sys.executable, filepath], stderr=subprocess.STDOUT, timeout=30)
            return result.decode('utf-8')
        except subprocess.CalledProcessError as e:
            return f"I tried to run the skill, but it failed: {e.output.decode('utf-8')}"
        except Exception as e:
            return f"Execution error: {str(e)}"